// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacificStarBackend.Data;

#nullable disable

namespace PacificStarBackend.Migrations
{
    [DbContext(typeof(PacificStarDbContext))]
    partial class PacificStarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PacificStarBackend.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraEncendido")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_encendido");

                    b.Property<decimal>("NivelCombustible")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("nivel_combustible");

                    b.Property<int>("NumeroUnidad")
                        .HasColumnType("int")
                        .HasColumnName("numero_unidad");

                    b.Property<decimal>("TempFinal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperatura_final");

                    b.Property<decimal>("TempInicial")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperatura_inicial");

                    b.HasKey("Id");

                    b.HasIndex("NumeroUnidad");

                    b.ToTable("bitacoras", (string)null);
                });

            modelBuilder.Entity("PacificStarBackend.Models.Unidad", b =>
                {
                    b.Property<int>("NumeroUnidad")
                        .HasColumnType("int")
                        .HasColumnName("numero_unidad");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("HorasMotor")
                        .HasColumnType("int")
                        .HasColumnName("horas_motor");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.HasKey("NumeroUnidad");

                    b.ToTable("unidades", (string)null);
                });

            modelBuilder.Entity("PacificStarBackend.Models.Bitacora", b =>
                {
                    b.HasOne("PacificStarBackend.Models.Unidad", "Unidad")
                        .WithMany("Bitacoras")
                        .HasForeignKey("NumeroUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("PacificStarBackend.Models.Unidad", b =>
                {
                    b.Navigation("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
